### ISSUE TITLE
hd_strip weirdness.

### ISSUE THREAD

**Issue by Accensus** [MatthewTheGlutton/HideousDestructor#81] opened 2020-01-31 20:42 UTC
Dunno how to explain it simply. Here's the steps to reproduce instead:
1. Bind a key to hd_strip for ease of access.
2. Acquire both a backpack and an armor. Any armor would do. Don't equip it.
3. Use hd_strip. You'll probably get the "Take off your backpack first" message.
4. Keep using it. After the 4th or 5th message, you will drop your backpack. The next usage of hd_strip will equip the armor.

**Comment by MatthewTheGlutton** [comment] 2020-01-31 20:46
What's the expected result?

**Comment by Accensus** [comment] 2020-01-31 20:50
I'd expect nothing would happen as hd_strip in itself doesn't imply equipping an armor. I'm not even sure what's intended and what isn't. It's convenient, at least.

**Comment by TwelveEyes** [comment] 2020-01-31 20:54
I always thought that was intended. You can equip armor in your inventory with `hd_strip` when you're not wearing armor. It also makes swapping worn armor with spare armor in your inventory real convenient.

**Comment by Accensus** [comment] 2020-01-31 20:56
What I'm actually reporting, I suppose, is having to press the key multiple times before something happens.

**Comment by MatthewTheGlutton** [comment] 2020-01-31 20:59
I'll take a look at it... been wanting to unify the various remove armour/remove backpack/remove radsuit functions for a while.

**Comment by boogiebogus** [comment] 2020-01-31 21:01
a double tap on HD_Strip seems to remove the backpack reliably

**Comment by caligari87** [comment] 2020-01-31 21:05
The way it's always seemed to work (and IIRC the intended way based on when this functionality was implemented) is that `hd_strip`, despite the name, is more of a contextual "do something logical with what you're wearing" command/button. For armor, that's strip it off. If you're not wearing armor, it doubles as putting armor on, for convenience. If something is preventing you from taking off the armor (backpack, radsuit), a double-tap is required to remove that item.

Personally I like the current paradigm and have not had any trouble with it. Seems to make sense to me.

**Comment by MatthewTheGlutton** [comment] 2020-01-31 21:08
oh, right, the double-tap override.

Calling hd_strip should not need that, I don't think.

I'll need to reconsider how to approach this... which might just leave me leaving this alone for another year

**Comment by Accensus** [comment] 2020-01-31 21:09
I didn't know about the double-tap. That reliably removes the backpack without the message appearing multiple times. I suppose this is closeable, unless Matt has anything in mind. Thanks, Cali.

**Comment by MatthewTheGlutton** [comment] 2020-02-01 00:52
So I just looked up the code and was reminded that hd_strip is just an alias for "use HDArmour; drop HDArmourWorn" which is why it's responding to the autostrip cvar.

Looking at the other code I see the armour-stripping stuff is already relatively well contained anyway, so given no one's clamouring for any big changes I'll close this without any changes.

**Closed by MatthewTheGlutton** 2020-02-01 00:52 UTC
